routes/web.php
<?php
use App\UserType;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

 // Authentication Routes...
 Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
 Route::post('login', 'Auth\LoginController@login');
 Route::post('logout', 'Auth\LoginController@logout')->name('logout');

//  // Registration Routes...
//  Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
//  Route::post('register', 'Auth\RegisterController@register');

//  // Password Reset Routes...
//  Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
//  Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
//  Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
//  Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::group(['middleware' => 'auth'], function()
{
    Route::redirect('/', '/target');
    Route::get('mykoor', 'KoorController@myKoor')->name('mykoor');
    Route::get('mysaksi', 'SaksiController@mySaksi')->name('mysaksi');
    Route::get('pengumumanku', 'PengumumanController@pengumumanku')->name('pengumumanku');
    Route::get('c1saya', 'C1Controller@c1Saya')->name('c1saya');
    Route::get('akunsaya', 'UserController@akunSaya')->name('akunsaya');
    Route::get('akunsaya/edit', 'UserController@editProfilSaya')->name('editprofil');
    Route::get('/kel/{id}', 'SaksiController@getKoor')->name('getkoor');
    Route::get('/checkpassword/{password}', 'UserController@checkPassword')->name('checkpassword');
    Route::get('/statuspengumuman/{id}/{boolean}', 'PengumumanController@updateStatus')->name('statuspengumuman');

    Route::resource('koor', 'KoorController');
    Route::resource('saksi', 'SaksiController');
    Route::resource('pengumuman', 'PengumumanController');
    Route::resource('user', 'UserController')->only([
        'index', 'show', 'update'
    ]);
    Route::resource('partai', 'PartaiController')->except(['show']);
    Route::resource('c1', 'C1Controller')->except(['show']);
    Route::resource('target', 'TargetController')->only([
        'index', 'edit', 'update'
    ]);
    // Route::get('/sms', function () {
    //     Nexmo::message()->send([
    //         'to'   => '6282247973615',
    //         'from' => '15556666666',
    //         'text' => 'SMS Send with Nexmo'
    //     ]);
    // });
    Route::fallback(function(){
        abort(404);
    });
});

app/Saksi.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Saksi extends Model
{
    protected $table = 'saksi';
    
    protected $fillable = [
        'user_id',
        'koor_id',
        'partai_id',
        'tps',
        'nama',
        'gender',
        'alamat',
        'no_hp',
        'foto_ktp',
        'foto_diri'
    ];

    public function koor()
    {
        return $this->belongsTo('App\Koor', 'koor_id');
    }
    
    public function user() {
        return $this->belongsTo('App\User', 'user_id');
    }

    public function partai()
    {
        return $this->belongsTo('App\Partai', 'partai_id');
    }

    public function c1() {
        return $this->hasOne('App\C1', 'saksi_id');
    }
}

app/Http/Controllers/SaksiController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Auth;
use App\Koor;
use App\Saksi;
use App\User;
use App\Kabupaten;
use App\Kelurahan;
use App\Partai;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use App\Http\Requests\ValidateSaksi;
use Image;

class SaksiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->ajax()) {
            $allSaksi = Saksi::with(['koor' => function($query) {
                            $query->select(['id','kel_id','nama']);
                        }, 'koor.kelurahan.kecamatan.kabupaten', 'partai'])->orderBy('created_at', 'DESC')
                        ->latest()->get(['id','koor_id','partai_id','tps','nama','gender','alamat','no_hp']);
            return json_encode(['data' => $allSaksi]);
        }
        else {
            $this->authorize('index', Saksi::class);
            return view('saksi.index');
        }
    }

    public function mySaksi(Request $request)
    {
        if($request->ajax()) {
            $kelId = Auth::user()->kelurahan->pluck('id')->toArray();
            $koorId = Koor::whereIn('kel_id', $kelId)->pluck('id')->toArray();
            $mySaksi = Saksi::with(['koor' => function($query) {
                            $query->select(['id','kel_id','nama']);
                        }, 'koor.kelurahan.kecamatan.kabupaten', 'partai'])
                        ->whereIn('koor_id', $koorId)
                        ->latest()->get(['id','koor_id','partai_id','tps','nama','gender','alamat','no_hp']);
            return json_encode(['data' => $mySaksi]);
        }
        else {
            $this->authorize('mySaksi', Saksi::class);
            return view('saksi.mysaksi');
        }

        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create', Saksi::class);
        $user = Auth::user();
        $partai = Partai::all();
        return view('saksi.create', compact('user','partai'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ValidateSaksi $request)
    {
        $saksiSatuTPS = Saksi::where('koor_id', $request['koor'])
                        ->where('tps', $request['notps'])
                        ->count();
        $koorSatuTPS = Koor::find($request['koor']);

        $saksiExist = Saksi::where(function ($query) use ($request){
                        $query->where('koor_id', $request['koor'])
                        ->where('partai_id', $request['partai'])
                        ->where('tps', $request['notps']);
                    })
                    ->where(function ($query) use ($request){
                        $query->where ('nama', $request['nama'])
                        ->where ('gender', $request['gender'])
                        ->where ('alamat', $request['alamat'])
                        ->where ('no_hp', $request['nohp']);
                    })
                    ->exists();
        if($saksiExist) {
            return redirect()->back()->withErrors(['Data Saksi sudah ada']);
        }
        else if($saksiSatuTPS == 2) {
            return \Redirect::route('saksi.create')
                    ->withErrors(['TPS-'.$request['notps'].' sudah ada 2 saksi dengan koordinator '.$koorSatuTPS->nama.''])
                    ->with('id', $koorSatuTPS->id);
        }
        else {
            $newPassword = random(8);
            do {
                $newUsername = random(8);
            }while(User::where('username', $newUsername)->exists());

            $newUser = User::create([
                'role_id'   => 4,
                'username'  => $newUsername,
                'password'  => \Hash::make($newPassword)
            ]);

            $resizeKtp = Image::make($request['fotoktp'])->orientate()->widen(600)->encode('jpg');
            $pathFotoKtp = $request['fotoktp']->hashName('public/saksi/foto_ktp');
            $fotoKtp = Storage::put($pathFotoKtp, (string) $resizeKtp);
            $fileFotoKtp = basename($pathFotoKtp);
            
            $resizeDiri = Image::make($request['fotodiri'])->orientate()->widen(600)->encode('jpg');
            $pathFotoDiri = $request['fotodiri']->hashName('public/saksi/foto_diri');
            $fotoDiri = Storage::put($pathFotoDiri, (string) $resizeDiri);
            $fileFotoDiri = basename($pathFotoDiri);

            $newSaksi = Saksi::create([
                'user_id'           => $newUser->id,
                'koor_id'           => $request['koor'],
                'partai_id'         => $request['partai'],
                'tps'               => $request['notps'],
                'nama'              => $request['nama'],
                'gender'            => $request['gender'],
                'alamat'            => $request['alamat'],
                'no_hp'             => $request['nohp'],
                'foto_ktp'          => $fileFotoKtp,
                'foto_diri'         => $fileFotoDiri
            ]);
            if($newUser->exists && $newSaksi->exists) {
                // \Nexmo::message()->send([
                //     'to'   => '6282247973615',
                //     'from' => '15556666666',
                //     'text' => 'Anda sdh terdaftar sbg Koordinator Saksi dgn username: '.$newUsername.' & password: '.$newPassword
                // ]);
                return \Redirect::route('saksi.create')
                    ->with('status', 'Data Saksi berhasil disimpan dengan username: '.$newUsername.' & password: '.$newPassword)
                    ->with('id', $newSaksi->id);
            }
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Saksi $saksi)
    {
        $this->authorize('view', $saksi);
        return view('saksi.show', compact('saksi'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Saksi $saksi)
    {
        $this->authorize('edit', $saksi);
        $user = Auth::user();
        $partai = Partai::all();
        return view('saksi.edit', compact('saksi', 'user', 'partai'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ValidateSaksi $request, Saksi $saksi)
    {
        $this->authorize('update', $saksi);
        
        if($request->hasFile('fotoktp')) {
            // STORE NEW ONE
            $resizeKtp = Image::make($request['fotoktp'])->orientate()->widen(600)->encode('jpg');
            $pathFotoKtp = $request['fotoktp']->hashName('public/saksi/foto_ktp');
            $fotoKtp = Storage::put($pathFotoKtp, (string) $resizeKtp);
            $fileFotoKtp = basename($pathFotoKtp);

            // DELETE OLD ONE
            Storage::delete('public/saksi/foto_ktp/'.$saksi->foto_ktp);

            // UPDATE DATABASE
            $saksi->update([
                'foto_ktp'          => $fileFotoKtp
            ]);
        }
        if ($request->hasFile('fotodiri')) {
            $resizeDiri = Image::make($request['fotodiri'])->orientate()->widen(600)->encode('jpg');
            $pathFotoDiri = $request['fotodiri']->hashName('public/saksi/foto_diri');
            $fotoDiri = Storage::put($pathFotoDiri, (string) $resizeDiri);
            $fileFotoDiri = basename($pathFotoDiri);

            Storage::delete('public/saksi/foto_diri/'.$saksi->foto_diri);

            $saksi->update([
                'foto_diri'          => $fileFotoDiri
            ]);
        }

        if(Auth::user()->id === $saksi->koor->kelurahan->kecamatan->user->id) {
            $saksi->update([
                'koor_id'           => $request['koor'],
                'partai_id'         => $request['partai'],
                'tps'               => $request['notps'],
                'nama'              => $request['nama'],
                'gender'            => $request['gender'],
                'alamat'            => $request['alamat'],
                'no_hp'             => $request['nohp']
            ]);

            if($saksi) {
                return back()->with('status', 'Data Saksi berhasil diupdate');
            }
        }
        else {
            $saksi->update([
                'nama'              => $request['nama'],
                'gender'            => $request['gender'],
                'alamat'            => $request['alamat'],
                'no_hp'             => $request['nohp']
            ]);

            if($saksi) {
                return back()->with('status', 'Data Saksi berhasil diupdate');
            }
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Saksi $saksi)
    {
        $this->authorize('delete', $saksi);

        Storage::delete('public/saksi/foto_ktp/'.$saksi->foto_ktp);
        Storage::delete('public/saksi/foto_diri/'.$saksi->foto_diri);

        $saksiIsDeleted = Saksi::destroy($saksi->id);
        User::destroy($saksi->user_id);

        $saksi = Saksi::first();
        if(!$saksi)
        {
            DB::update("ALTER TABLE saksi AUTO_INCREMENT= 1");
        }
        
        if($saksiIsDeleted) {
            if(app('router')->getRoutes()->match(app('request')->create(\URL::previous()))->getName() == "mysaksi") {
                return redirect()->route('mysaksi')->with('status', 'Data Saksi sudah dihapus');

resources/views/saksi/create.blade.php
@extends('layouts.app')
<head>
    @include('layouts.base')  
    <title>Tambah Saksi - Sistem Informasi Manajemen Saksi Pemilu</title>
    <link href="{{asset('css/select2.min.css')}}" rel="stylesheet" />
    <script src="{{asset('js/select2.min.js')}}"></script>
</head>

@section('content')
<div class="row">
    <div class="col-lg"></div>
    <div class="col-lg-9">
        @if (\Session::has('status'))
            <div class="alert alert-success fade show mb-4 px-3 py-2" role="alert">
                {{ \Session::get('status') }}
                <div class="d-flex justify-content-end my-2">
                    <a class="btn btn-small btn-light" href="{{\Session::get('id')}}">Lihat Profil Saksi</a>
                </div>
            </div>
        @endif
        @if ($errors->any())
            <div class="alert alert-danger fade show mb-4 px-3 py-2" role="alert">
                {{ $errors->first() }}
            </div>
        @endif

        <form method="POST" action="{{route('saksi.store')}}" enctype="multipart/form-data">
            @csrf
            <h3 class="text-center mb-5"><strong>Tambah Saksi</strong></h3>
            <div class="form-row">
            
                <!-- KABUPATEN/KOTA -->
                <div class="form-group col-md-4">
                    <label class="text-muted">Kabupaten/Kota</label>
                    <h5>{{$user->komisisaksi->kabupaten->nama}}</h5>
                </div>
            
                <!-- KECAMATAN -->
                <div class="form-group col-md-4">
                    <label class="text-muted">Kecamatan</label>
                    <h5>{{$user->komisisaksi->nama}}</h5>
                </div>
        
                <!-- DESA -->
                <div class="form-group col-md-4">
                    <label class="text-muted">Kelurahan/Desa</label>
                    <select class="form-control custom-select" id="kel" required>
                        <option value="" disabled selected>Pilih...</option>
                        @foreach($user->kelurahan as $kel)
                        <option value="{{$kel->id}}">{{$kel->nama}} ({{$kel->koor->count()}})</option>
                        @endforeach
                    </select>
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-12">
                    <label for="koor" class="text-muted mt-2">Koordinator</label>
                    <select class="form-control custom-select" id="koor" name="koor" required>
                        <option value="" disabled selected>Pilih...</option>
                        
                    </select>
                </div>

                <div class="form-group col-12">
                    <label for="partai" class="text-muted mt-3">Partai</label>
                    <select class="form-control custom-select" id="partai" name="partai" required>
                        <option value="" disabled selected>Pilih...</option>
                        @foreach($partai as $partai)
                            <option value="{{$partai->id}}">{{$partai->nama}}</option>
                        @endforeach
                    </select>
                </div>

                <div class="form-group col-12">
                    <label for="notps" class="text-muted mt-3">Nomor TPS</label>
                    <select class="form-control custom-select" id="notps" name="notps" required>
                        <option value="" disabled selected>Pilih...</option>
                        @for ($i = 1; $i <= 100; $i++)
                            <option value="{{ $i }}">TPS {{ $i }}</option>
                        @endfor
                    </select>
                </div>
            </div>
        
            <hr class="my-4 dashed-line">

            <div class="form-group">
                <label class="text-muted mt-3" for="nama">Nama Saksi</label>
                <input type="text" name="nama" class="form-control" id="nama" required>
            </div>

            <label class="text-muted mt-3">Jenis Kelamin</label>
            <div class="form-inline mb-3 ml-2">
                <div class="custom-control custom-radio mr-5 mt-2">
                    <input type="radio" id="genderL" name="gender" value="L" class="custom-control-input" required>
                    <label class="custom-control-label gender-label" for="genderL">Laki-Laki</label>
                </div>
                <div class="custom-control custom-radio mt-2">
                    <input type="radio" id="genderP" name="gender" value="P" class="custom-control-input" required>
                    <label class="custom-control-label gender-label" for="genderP">Perempuan</label>
                </div>
            </div>
        
            <div class="form-group">
                <label class="text-muted mt-3" for="alamat">Alamat Tempat Tinggal</label>
                <input type="text" name="alamat" class="form-control" id="alamat" required>
            </div>
        
            <div class="form-group">
                <label class="text-muted mt-3" for="nohp">Nomor Handphone / WhatsApp</label>
                <input type="tel" class="form-control" name="nohp" id="nohp" maxlength="15" required>
            </div>
        
            <div class="col-12 p-0 mb-3">
                <label class="text-muted mt-3" for="fotoktp">Foto KTP</label><br>
                <div id="file-upload" class="file-upload">
                    <div class="image-upload-wrap">
                        <input name="fotoktp" class="file-upload-input" type='file' onchange="readURL(this);" accept="image/*" required/>
                        <div class="drag-text">
                            <h3><i class="mdi mdi-plus"></i></h3>
                        </div>
                    </div>
                    <div class="file-upload-content" style="display:none;">
                        <img class="file-upload-image mb-1" src="#" alt="Foto KTP" /><br>
                        <small class="image-title"></small><br>
                        <button type="button" onclick="removeUpload()" class="btn btn-secondary mt-2">Ubah</button>
                    </div>
                </div>
            </div>
            <div class="col-12 p-0 ">
                <label class="text-muted mt-4" for="fotodiri">Foto Diri</label><br>
                <div id="file-upload2" class="file-upload">
                    <div class="image-upload-wrap">
                        <input name="fotodiri" class="file-upload-input" type='file' onchange="readURL2(this);" accept="image/*" required/>
                        <div class="drag-text">
                            <h3><i class="mdi mdi-plus"></i></h3>
                        </div>
                    </div>
                    <div class="file-upload-content" style="display:none;">
                        <img class="file-upload-image mb-1" src="#" alt="Foto Diri" /><br>
                        <small class="image-title"></small><br>
                        <button type="button" onclick="removeUpload2()" class="btn btn-secondary mt-2">Ubah</button>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col"></div>
                <div class="col-lg-4 col-md-4 col-sm-8 mt-3">
                    <button type="submit" class="btn btn-success btn-lg btn-block mt-4 font-weight-bold">SIMPAN</button>
                </div>
            </div>
        </form>
    </div>
    <div class="col-lg"></div>
</div>
<script src="{{asset('js/saksi_create.js')}}"></script>
<script src="{{asset('js/image-input.js')}}"></script>
@endsection

resources/views/saksi/show.blade.php
@extends('layouts.app')
<head>
    @include('layouts.base')
    <title>Detail Saksi - Sistem Informasi Manajemen Saksi Pemilu</title>
    <meta name="csrf-token" content="{{ csrf_token() }}" />
</head>

@section('content')
<div class="d-flex justify-content-center">
    <div class="d-flex flex-container flex-column">
        @if (\Session::has('status'))
        <div class="alert alert-success fade show mb-4 px-3 py-2" role="alert">
            {{ \Session::get('status') }}
        </div>
        @endif
        @if ($errors->any())
            <div class="alert alert-danger fade show mb-4 px-3 py-2" role="alert">
                {{ $errors->first() }}
            </div>
        @endif
        <div class="d-flex justify-content-center">
            <h3 class="m-0 text-center"><strong>Detail Saksi</strong></h3>
        </div>
        <hr>
        @if($saksi->koor->kelurahan->kecamatan->user->id === Auth::user()->id)
        <div class="d-flex flex-row justify-content-end mb-3">
            <a class="btn btn-success mr-2" href="{{route('saksi.edit', $saksi->id)}}" title="Edit">
                <i class="mdi mdi-pencil"></i> Edit
            </a>
            <button type="button" class="btn btn-danger" title="Hapus" data-toggle="modal" data-target="#modalHapusSaksi">
                <i class="mdi mdi-delete"></i> Hapus
            </button>
            <!-- Modal Hapus-->
            <div class="modal fade" id="modalHapusSaksi" tabindex="-1" role="dialog" aria-labelledby="modalTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered modal-dialog modal-sm" role="document">
                    <div class="modal-content border-0">
                        <div class="modal-body p-4">
                            <h5 class="font-weight-bold m-0">Hapus saksi ini?</h5>
                        </div>
                        <div class="modal-footer border-0">
                            <button type="button" class="btn btn-light mr-2" data-dismiss="modal">Tidak</button>
                            <form action="{{route('saksi.destroy', $saksi->id)}}" method="POST" class="m-0">
                                @csrf
                                @method('DELETE')
                                <input name="_method" type="hidden" value="DELETE">
                                <button type="submit" class="btn btn-danger">Hapus</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @endif
        <div class="d-flex flex-column flex-sm-row justify-content-between">
            <div class="d-flex flex-column flex-grow-1">
                <div class="card card-radius card-margin p-4">
                    <h5 class="card-title font-weight-bold mb-3 text-center">PROFIL SAKSI</h5>
                    <a href="{{ asset("storage/saksi/foto_diri/{$saksi->foto_diri}") }}" class="mt-2 mb-3">
                        <img class="foto" src="{{ asset("storage/saksi/foto_diri/{$saksi->foto_diri}") }}" alt="Foto Diri Saksi">
                    </a>
                    <small class="text-muted mt-2 mb-1">Nama</small>
                    <p class="mb-3"><strong>{{$saksi->nama}}</strong></p>
    
                    <small class="text-muted mb-1">Jenis Kelamin</small>
                    <p class="mb-3"><strong>
                        {{$saksi->gender === "L" ? "Laki-Laki" : "Perempuan"}}
                    </strong></p>
    
                    <small class="text-muted mb-1">Alamat Tempat Tinggal</small>
                    <p class="mb-3"><strong>{{$saksi->alamat}}</strong></p>
    
                    <small class="text-muted mb-1">Nomor Handphone</small>
                    <p class="mb-3"><strong>{{$saksi->no_hp}}</strong></p>

                    <small class="text-muted mb-1">Partai</small>
                    <p class="mb-3"><strong>{{$saksi->partai->nama}}</strong></p>
    
                    <small class="text-muted mb-1">Foto KTP</small>
                    <a href="{{ asset("storage/saksi/foto_ktp/{$saksi->foto_ktp}") }}">
                        <img src="{{ asset("storage/saksi/foto_ktp/{$saksi->foto_ktp}") }}" alt="Foto Diri Saksi" width="150px">
                    </a>
                </div>
            </div>
            <div class="d-flex flex-column">
                <div class="card card-radius mb-3 p-4">
                    <h5 class="card-title font-weight-bold mb-3 text-center">DAERAH</h5>
                    <small class="text-muted mt-2 mb-1">Kabupaten/Kota</small>
                    <p class="mb-3"><strong>{{$saksi->koor->kelurahan->kecamatan->kabupaten->nama}}</strong></p>
                    <small class="text-muted mb-1">Kecamatan</small>
                    <p class="mb-3"><strong>{{$saksi->koor->kelurahan->kecamatan->nama}}</strong></p>
                    <small class="text-muted mb-1">Kelurahan</small>
                    <p class="mb-3"><strong>{{$saksi->koor->kelurahan->nama}}</strong></p>
                    <h4 class="mb-0"><strong><span class="badge badge-dark rounded-0 p-2">TPS {{$saksi->tps}}</span></strong></h4>
                </div>
                <div class="card card-radius mb-3 p-4">
                    <h5 class="card-title font-weight-bold mb-3 text-center">KOORDINATOR</h5>
                    <a href="{{ asset("storage/koor/foto_diri/{$saksi->koor->foto_diri}") }}" class="mt-1 mb-2">
                        <img style="height:100px;" src="{{ asset("storage/koor/foto_diri/{$saksi->koor->foto_diri}") }}" alt="Foto Diri Saksi">
                    </a>
                    <small class="text-muted mt-2 mb-1">Nama</small>
                    <p class="mb-3"><strong>{{$saksi->koor->nama}}</strong></p>

                    <small class="text-muted mb-1">Nomor Handphone</small>
                    <p class="mb-3"><strong>{{$saksi->koor->no_hp}}</strong></p>
        
                    <a href="{{route('koor.show', $saksi->koor->id)}}" class="btn btn-secondary mt-2 align-self-end">Detail</a>
                </div>
                @if($saksi->koor->kelurahan->kecamatan->user->id === Auth::user()->id)
                <div class="card card-radius mb-3 p-4">
                    <h5 class="card-title font-weight-bold text-center mb-3">AKUN SAKSI</h5>
                    <small class="text-muted mt-2 mb-1">Username</small>
                    <div class="d-flex justify-content-start">
                        <button id="btn-reset-username" class="btn btn-secondary btn-small mb-3" type="button" data-toggle="modal" data-target="#modal-reset">
                            <i class="mdi mdi-account-convert"></i> Reset Username
                        </button>
                    </div>
                    <small class="text-muted mt-2 mb-1">Password</small>
                    <div class="d-flex justify-content-start">
                        <button id="btn-reset-password" class="btn btn-secondary btn-small" type="button" data-toggle="modal" data-target="#modal-reset">
                            <i class="mdi mdi-lock-reset"></i> Reset Password
                        </button>
                    </div>

                    {{-- Modal RESET --}}
                    <div class="modal fade" id="modal-reset" tabindex="-1" role="dialog" aria-labelledby="modalTitle" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered modal-dialog modal-sm" role="document">
                            <div class="modal-content border-0">
                                <div class="modal-body p-4">
                                    <h5 id="reset-title" class="font-weight-bold m-0"></h5>
                                </div>
                                <div class="modal-footer border-0">
                                    <button type="button" class="btn btn-light mr-2" data-dismiss="modal">Tidak</button>
                                    <form id="form-reset" action="{{route('user.update', $saksi->user->id)}}" method="POST" class="m-0"  enctype="multipart/form-data">
                                        @csrf
                                        @method('PUT')
                                        
                                        <button id="btn-reset" type="submit" class="btn btn-primary">Reset</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                @endif
            </div>
        </div>
    </div>
</div>
@if($saksi->koor->kelurahan->kecamatan->user->id === Auth::user()->id)
<script>
    $(document).ready(function() {
        $("#btn-reset-username").click(function() {
            $("#reset-title").html("Reset username saksi ini?");
            $('<input name="reset-username" type="hidden">').insertBefore("#btn-reset");
        });
        $("#btn-reset-password").click(function() {
            $("#reset-title").html("Reset password saksi ini?");
            $('<input name="reset-password" type="hidden">').insertBefore("#btn-reset");
        });
    });
</script>
@endif
@endsection