routes/web.php
<?php
use App\UserType;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

 // Authentication Routes...
 Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
 Route::post('login', 'Auth\LoginController@login');
 Route::post('logout', 'Auth\LoginController@logout')->name('logout');

//  // Registration Routes...
//  Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
//  Route::post('register', 'Auth\RegisterController@register');

//  // Password Reset Routes...
//  Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
//  Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
//  Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
//  Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::group(['middleware' => 'auth'], function()
{
    Route::redirect('/', '/target');
    Route::get('mykoor', 'KoorController@myKoor')->name('mykoor');
    Route::get('mysaksi', 'SaksiController@mySaksi')->name('mysaksi');
    Route::get('pengumumanku', 'PengumumanController@pengumumanku')->name('pengumumanku');
    Route::get('c1saya', 'C1Controller@c1Saya')->name('c1saya');
    Route::get('akunsaya', 'UserController@akunSaya')->name('akunsaya');
    Route::get('akunsaya/edit', 'UserController@editProfilSaya')->name('editprofil');
    Route::get('/kel/{id}', 'SaksiController@getKoor')->name('getkoor');
    Route::get('/checkpassword/{password}', 'UserController@checkPassword')->name('checkpassword');
    Route::get('/statuspengumuman/{id}/{boolean}', 'PengumumanController@updateStatus')->name('statuspengumuman');

    Route::resource('koor', 'KoorController');
    Route::resource('saksi', 'SaksiController');
    Route::resource('pengumuman', 'PengumumanController');
    Route::resource('user', 'UserController')->only([
        'index', 'show', 'update'
    ]);
    Route::resource('partai', 'PartaiController')->except(['show']);
    Route::resource('c1', 'C1Controller')->except(['show']);
    Route::resource('target', 'TargetController')->only([
        'index', 'edit', 'update'
    ]);
    // Route::get('/sms', function () {
    //     Nexmo::message()->send([
    //         'to'   => '6282247973615',
    //         'from' => '15556666666',
    //         'text' => 'SMS Send with Nexmo'
    //     ]);
    // });
    Route::fallback(function(){
        abort(404);
    });
});

app/C1.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class C1 extends Model
{
    protected $table = 'c1';
    
    protected $fillable = [
        'saksi_id',
        'foto_c1'
    ];

    public function saksi() {
        return $this->belongsTo('App\Saksi', 'saksi_id');
    }
}

app/Http/Controllers/C1Controller.php
<?php

namespace App\Http\Controllers;

use Auth;
use App\C1;
use App\User;
use App\Saksi;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class C1Controller extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->ajax()) {
            $allC1 = C1::with(['saksi' => function($query) {
                            $query->select(['id','koor_id','tps','nama']);
                        }, 'saksi.koor.kelurahan.kecamatan.kabupaten'])->orderBy('created_at', 'DESC')
                        ->latest()->get();
            return json_encode(['data' => $allC1]);
        }
        else {
            $this->authorize('index', C1::class);
            return view('c1.index');
        }
    }

    public function c1Saya() {
        $this->authorize('c1Saya', C1::class);
        $user = User::find(Auth::id());
        return view('c1.c1saya', compact('user'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create', C1::class);
        $user = User::find(Auth::id());
        if($user->saksi->c1) {
            abort(403, "Anda sudah mengupload 1 foto formulir C1");
        }
        return view('c1.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $request->validate([
                'foto_c1'   => 'required|file|mimes:jpeg,jpg,bmp,png|max:5000',
            ]);
            $user = User::find(Auth::id());
    
            $tps = 'TPS-'.$user->saksi->tps;
            $kel = $user->saksi->koor->kelurahan->nama;
            $realName = basename($request->file('foto_c1')->getClientOriginalName(), '.'.$request->file('foto_c1')->getClientOriginalExtension());
            $uniqueName = $tps . '-' . $kel . '_' . $realName . '_'.time().'.' . $request->file('foto_c1')->getClientOriginalExtension();
            $file = $request->file('foto_c1')->storeAs('public/c1', $uniqueName,'local');
    
            $newC1 = C1::create([
                'saksi_id'  => $user->saksi->id,
                'foto_c1'   => $uniqueName
            ]);
            return redirect()->route('c1saya')->with('status', 'Foto C1 berhasil disimpan');
        }
        catch(\Exception $exception) {
            abort(403, $exception->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\C1  $c1
     * @return \Illuminate\Http\Response
     */
    public function show(C1 $c1)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\C1  $c1
     * @return \Illuminate\Http\Response
     */
    public function edit(C1 $c1)
    {
        $this->authorize('edit', $c1);
        return view('c1.edit', compact('c1'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\C1  $c1
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, C1 $c1)
    {
        $this->authorize('update', $c1);
        if($request->has('foto_c1')) {
            try {
                $request->validate([
                    'foto_c1'   => 'required|file|mimes:jpeg,jpg,bmp,png|max:5000',
                ]);
                $user = User::find(Auth::id());
        
                $tps = 'TPS-'.$user->saksi->tps;
                $kel = $user->saksi->koor->kelurahan->nama;
                $realName = basename($request->file('foto_c1')->getClientOriginalName(), '.'.$request->file('foto_c1')->getClientOriginalExtension());
                $uniqueName = $tps . '-' . $kel . '_' . $realName . '_'.time().'.' . $request->file('foto_c1')->getClientOriginalExtension();            
                $file = $request->file('foto_c1')->storeAs('public/c1', $uniqueName,'local');
    
                Storage::delete('public/c1/'.$c1->foto_c1);
        
                $c1->update([
                    'foto_c1'   => $uniqueName
                ]);
                return back()->with('status', 'Foto C1 berhasil diupdate');
            }
            catch(\Exception $exception) {
                abort(403, $exception->getMessage());
            }
        }
        else {
            return back()->with('status', 'Foto C1 berhasil diupdate');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\C1  $c1
     * @return \Illuminate\Http\Response
     */
    public function destroy(C1 $c1)
    {
        $this->authorize('delete', $c1);
        Storage::delete('public/c1/'.$c1->foto_c1);
        $isDeleted = C1::destroy($c1->id);
        
        if(!C1::first()) {
            DB::update("ALTER TABLE c1 AUTO_INCREMENT= 1");
        }
        if($isDeleted) {
            return back()->with('status', 'Foto C1 berhasil dihapus');
        }
    }
}

resources/views/c1/c1saya.blade.php
@extends('layouts.app')
<head>
    @include('layouts.base')
    <title>Foto C1 Saya - Sistem Informasi Manajemen Saksi Pemilu</title>
</head>

@section('content')
<div class="row">
    <div class="col-lg"></div>
    <div class="col-lg-9">
        @if (\Session::has('status'))
            <div class="alert alert-success fade show mb-4 px-3 py-2" role="alert">
                {{ \Session::get('status') }}
            </div>
        @endif
        @if ($errors->any())
            <div class="alert alert-danger fade show mb-4 px-3 py-2" role="alert">
                {{ $errors->first() }}
            </div>
        @endif
    </div>
    <div class="col-lg"></div>
</div>
<h3 class="text-center mb-3"><strong>Foto C1 Saya</strong></h3>
    
<div class="d-flex justify-content-center">
    @if($user->saksi->c1)
    <div class="d-flex flex-container flex-column flex-sm-row">
        <div class="flex-fill text-center card align-self-sm-start card-radius m-2 p-4">
            <a href="{{ asset("storage/c1/{$user->saksi->c1->foto_c1}") }}">
                <img src="{{ asset("storage/c1/{$user->saksi->c1->foto_c1}") }}" alt="Foto Diri Saksi" style="max-width:400px;width:100%;">
            </a>
            <div class="d-flex flex-row justify-content-end mt-3">
                <a href="{{route('c1.edit', $user->saksi->c1->id)}}" class="btn flex-fill btn-success align-self-end mr-2">Edit</a>
                <button type="button" class="btn flex-fill btn-danger align-self-end ml-2" title="Hapus" data-toggle="modal" data-target="#modal-hapus">Hapus
                </button>
                <!-- Modal Hapus-->
                <div class="modal fade" id="modal-hapus" tabindex="-1" role="dialog" aria-labelledby="modalTitle" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered modal-dialog modal-sm" role="document">
                        <div class="modal-content border-0">
                            <div class="modal-body p-4">
                                <h5 class="text-left font-weight-bold m-0">Hapus Foto C1?</h5>
                            </div>
                            <div class="modal-footer border-0">
                                <button type="button" class="btn btn-light mr-2" data-dismiss="modal">Tidak</button>
                                <form action="{{route('c1.destroy', $user->saksi->c1->id)}}" method="POST" class="m-0">
                                    @csrf
                                    @method('DELETE')
                                    <input name="_method" type="hidden" value="DELETE">
                                    <button type="submit" class="btn btn-danger">Hapus</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="flex-fill align-self-sm-start card card-radius m-2 p-4">
            <small class="text-muted mt-2 mb-1">Kabupaten/Kota</small>
            <p class="mb-3"><strong>{{$user->saksi->koor->kelurahan->kecamatan->kabupaten->nama}}</strong></p>
            <small class="text-muted mb-1">Kecamatan</small>
            <p class="mb-3"><strong>{{$user->saksi->koor->kelurahan->kecamatan->nama}}</strong></p>
            <small class="text-muted mb-1">Kelurahan</small>
            <p class="mb-3"><strong>{{$user->saksi->koor->kelurahan->nama}}</strong></p>
            <h4 class="mb-0"><strong><span class="badge badge-dark rounded-0 p-2">TPS {{$user->saksi->tps}}</span></strong></h4>
        </div>
    </div>
    @else
    <div class="d-flex flex-container justify-content-center">
        <div class="text-center card align-self-center card-radius m-2 p-5">
            <small class="m-0 text-muted">Tidak ada foto formulir C1</small>
            <a href="{{route('c1.create')}}" class="btn btn-success btn-block mt-3 align-self-end"><i class="mdi mdi-upload"></i> Upload Foto C1</a>
        </div>
    </div>
    @endif
</div>
@endsection

resources/views/c1/create.blade.php
@extends('layouts.app')
<head>
    @include('layouts.base')  
    <title>Tambah Foto Formulir C1 - Sistem Informasi Manajemen Saksi Pemilu</title>
</head>

@section('content')
<div class="row">
    <div class="col-lg"></div>
    <div class="col-lg-9">
        @if (\Session::has('status'))
            <div class="alert alert-success fade show mb-4 px-3 py-2" role="alert">
                {{ \Session::get('status') }}
            </div>
        @endif
        @if ($errors->any())
            <div class="alert alert-danger fade show mb-4 px-3 py-2" role="alert">
                {{ $errors->first() }}
            </div>
        @endif

        <form method="POST" action="{{route('c1.store')}}" enctype="multipart/form-data">
            @csrf
            <h3 class="text-center"><strong>Tambah Foto Formulir C1</strong></h3>
        
            <label class="text-muted my-3" for="foto_c1">Foto Formulir C1</label>
            <div id="file-upload" class="file-upload">
                <div class="image-upload-wrap">
                    <input name="foto_c1" class="file-upload-input" type='file' onchange="readURL(this);" accept="image/*" required/>
                    <div class="drag-text">
                        <h3><i class="mdi mdi-plus"></i></h3>
                    </div>
                </div>
                <div class="file-upload-content" style="display:none;">
                    <img class="file-upload-image mb-1" src="#" alt="your image" /><br>
                    <small class="image-title"></small><br>
                    <button type="button" onclick="removeUpload()" class="btn btn-secondary mt-2">Ubah</button>
                </div>
            </div>

            <div class="row">
                <div class="col"></div>
                <div class="col-lg-4 col-md-4 col-sm-8 mt-3">
                    <button type="submit" class="btn btn-success btn-lg btn-block mt-4 font-weight-bold">SIMPAN</button>
                </div>
            </div>
        </form>
    </div>
    <div class="col-lg"></div>
</div>
<script src="{{asset('js/image-input.js')}}"></script>
@endsection

resources/views/c1/edit.blade.php
@extends('layouts.app')
<head>
    @include('layouts.base')  
    <title>Edit Foto Formulir C1 - Sistem Informasi Manajemen Saksi Pemilu</title>
</head>

@section('content')
<div class="row">
    <div class="col-lg"></div>
    <div class="col-lg-9">
        @if (\Session::has('status'))
            <div class="alert alert-success fade show mb-4 px-3 py-2" role="alert">
                {{ \Session::get('status') }}
            </div>
        @endif
        @if ($errors->any())
            <div class="alert alert-danger fade show mb-4 px-3 py-2" role="alert">
                {{ $errors->first() }}
            </div>
        @endif

        <form method="POST" action="{{route('c1.update', $c1->id)}}" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <h3 class="text-center"><strong>Edit Foto Formulir C1</strong></h3>
        
            <label class="text-muted my-3" for="foto_c1">Foto Formulir C1</label>
            <div class="file-upload">
                <div class="image-upload-wrap" style="display:none;">
                    <input name="foto_c1" class="file-upload-input" type='file' onchange="readURL(this);" accept="image/*"/>
                    <div class="drag-text">
                        <h3><i class="mdi mdi-plus"></i></h3>
                    </div>
                </div>
                <div class="file-upload-content">
                    <a href="{{ asset("storage/c1/{$c1->foto_c1}") }}">
                        <img class="file-upload-image mb-1" src="{{ asset("storage/c1/{$c1->foto_c1}") }}" alt="your image" /><br>
                    </a>
                    <small class="image-title">{{$c1->foto_c1}}</small><br>
                    <button type="button" onclick="removeUpload()" class="btn btn-secondary mt-2">Ubah</button>
                </div>
            </div>

            <div class="row">
                <div class="col"></div>
                <div class="col-lg-4 col-md-4 col-sm-8 mt-3">
                    <button type="submit" class="btn btn-success btn-lg btn-block mt-4 font-weight-bold">SIMPAN</button>
                </div>
            </div>
        </form>
    </div>
    <div class="col-lg"></div>
</div>
<script src="{{asset('js/image-input.js')}}"></script>
@endsection

resources/views/c1/index.blade.php
@extends('layouts.app')
<head>
    @include('layouts.base')
    @include('layouts.datatable-css')
    @include('layouts.datatable-js')
    @include('layouts.datatable-btn-js')
    <title>Foto Formulir C1 - Sistem Informasi Manajemen Saksi Pemilu</title>
    <meta name="csrf-token" content="{{ csrf_token() }}" />
    <style>
        .dt-buttons.btn-group > button:first-child {
            border-top-right-radius: 25px !important;
            border-bottom-right-radius: 25px !important;
        }
    </style>
</head>

@section('content')
<div class="row">
    <div class="col-12">
        @if (\Session::has('status'))
            <div class="alert alert-success fade show mb-4 px-3 py-2" role="alert">
                {{ \Session::get('status') }}
            </div>
        @endif
        @if ($errors->any())
            <div class="alert alert-danger fade show mb-4 px-3 py-2" role="alert">
                {{ $errors->first() }}
            </div>
        @endif
        <h3 class="text-center"><strong>Foto Formulir C1</strong></h3>
        <hr>
    </div>
</div>

<div class="d-flex flex-column flex-md-row justify-content-between align-content-center">
    <form id="global-search-form" class="d-flex align-items-center flex-fill p-0 mb-2">
        <i class="mdi mdi-magnify mdi-24px pr-1"></i>
        <input id="globalSearch" class="form-control m-0" type="text" placeholder="Cari..." maxlength="100">
    </form>
    <div id="tableOptionBtn" class="ml-2"></div>
</div>
    
<div class="row">
    <div class="col">
        <div class="table-responsive">
            <table id="tabelC1" class="align-self-center table table-hover table-responsive table-bordered table-striped" style="width:100%">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Kabupaten/Kota</th>
                        <th>Kecamatan</th>
                        <th>Kelurahan</th>
                        <th>Nomor TPS</th>
                        <th>Nama Saksi</th>
                        <th>Foto C1</th>
                    </tr>
                </thead>
                <tbody>
                    
                </tbody>
                <tfoot>
                    <tr>
                        <th>#</th>
                        <th><input type="text" placeholder="Kabupaten/Kota" style="width:100%"/></th>
                        <th><input type="text" placeholder="Kecamatan" style="width:100%"/></th>
                        <th><input type="text" placeholder="Kelurahan" style="width:100%"/></th>
                        <th><input type="text" placeholder="Nomor TPS" style="width:100%"/></th>
                        <th><input type="text" placeholder="Nama Saksi" style="width:100%"/></th>
                        <th>Foto C1</th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>
<div class="d-flex flex-column">
    <div id="tableInfo" class="d-flex justify-content-center my-2"></div>
    <div id="tablePage" class="d-flex justify-content-center"></div>
</div>


<script>
    $(document).ready(function() {
        $.fn.DataTable.ext.pager.numbers_length = 5;
        var table = $('#tabelC1').DataTable({
            processing: true,
            ajax: '{{route("c1.index")}}',
            columns: [
                { "data": null },
                { "data": "saksi.koor.kelurahan.kecamatan.kabupaten.nama" },
                { "data": "saksi.koor.kelurahan.kecamatan.nama" },
                { "data": "saksi.koor.kelurahan.nama" },
                { "data": "saksi.tps" },
                { "data": "saksi" },
                { "data": "foto_c1" },
            ],
            columnDefs: [
                { orderable: false, targets: [0,-1] },
                {
                    "targets": -2,
                    "data": "saksi",
                    "render": function ( data, type, row, meta ) {
                    return '<a href="saksi/'+data.id+'" class="table-link">'+data.nama+'</a>';
                    }
                },
                {
                    "targets": -1,
                    "data": "foto_c1",
                    "render": function ( data, type, row, meta ) {
                    return '<a href="storage/c1/'+data+'">'+
                                '<img src="storage/c1/'+data+'" alt="Foto C1" height="100px">'+
                            '</a>';
                    }
                },
            ],
            order: [],
            autoWidth: true,
            language: {
                "info": "_START_-_END_ dari _TOTAL_ data",
                "infoEmpty":  "Tidak Ada Data",
                "emptyTable": "Tidak ada data yang tersedia",
                "lengthMenu": "Tampilkan _MENU_ data",
                "thousands":      ".",
                'loadingRecords': '&nbsp;',
                "processing": "<div class='spinner'></div>",
                "search":     "Cari:",
                "zeroRecords":"Tidak ada data",
                "infoFiltered":   "(disaring dari total _MAX_ data)",
                "paginate": {
                    "next":       "<i class='mdi mdi-chevron-right'></i>",
                    "previous":   "<i class='mdi mdi-chevron-left'></i>"
                },
            },
            pagingType: "simple_numbers",
            pageLength: 10,
            lengthChange: false,
            dom: 'Brt<"row"<"col-sm-12 col-md-5"i><"col-sm-12 col-md-7"p>>',
            buttons: [ 
                {
                    text: "<i class='mdi mdi-eye'></i> Kolom",
                    extend: 'colvis',
                },
            ],
        });

        table.on( 'order.dt search.dt', function () {
            table.column(0, {search:'applied', order:'applied'}).nodes().each( function (cell, i) {
                cell.innerHTML = i+1;
            } );
        } ).draw();

        // TABLE SEARCH (GLOBAL)
        $('#globalSearch').on( 'keyup', function () {
            table.search( this.value ).draw();
        });

        // COLUMN SEARCH
        table.columns().every( function () {
            var that = this;
            $( 'input', this.footer() ).on( 'keyup change', function () {
                if ( that.search() !== this.value ) {
                    that.search( this.value ).draw();
                }
            });
        });

        table.buttons().container()
        .appendTo( '#tableOptionBtn' );
        $('.dataTables_paginate').appendTo('#tablePage');
        $('.dataTables_info').appendTo('#tableInfo');
    });
</script>
@endsection