routes/web.php
<?php
use App\UserType;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

 // Authentication Routes...
 Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
 Route::post('login', 'Auth\LoginController@login');
 Route::post('logout', 'Auth\LoginController@logout')->name('logout');

//  // Registration Routes...
//  Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
//  Route::post('register', 'Auth\RegisterController@register');

//  // Password Reset Routes...
//  Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
//  Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
//  Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
//  Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::group(['middleware' => 'auth'], function()
{
    Route::redirect('/', '/target');
    Route::get('mykoor', 'KoorController@myKoor')->name('mykoor');
    Route::get('mysaksi', 'SaksiController@mySaksi')->name('mysaksi');
    Route::get('pengumumanku', 'PengumumanController@pengumumanku')->name('pengumumanku');
    Route::get('c1saya', 'C1Controller@c1Saya')->name('c1saya');
    Route::get('akunsaya', 'UserController@akunSaya')->name('akunsaya');
    Route::get('akunsaya/edit', 'UserController@editProfilSaya')->name('editprofil');
    Route::get('/kel/{id}', 'SaksiController@getKoor')->name('getkoor');
    Route::get('/checkpassword/{password}', 'UserController@checkPassword')->name('checkpassword');
    Route::get('/statuspengumuman/{id}/{boolean}', 'PengumumanController@updateStatus')->name('statuspengumuman');

    Route::resource('koor', 'KoorController');
    Route::resource('saksi', 'SaksiController');
    Route::resource('pengumuman', 'PengumumanController');
    Route::resource('user', 'UserController')->only([
        'index', 'show', 'update'
    ]);
    Route::resource('partai', 'PartaiController')->except(['show']);
    Route::resource('c1', 'C1Controller')->except(['show']);
    Route::resource('target', 'TargetController')->only([
        'index', 'edit', 'update'
    ]);
    // Route::get('/sms', function () {
    //     Nexmo::message()->send([
    //         'to'   => '6282247973615',
    //         'from' => '15556666666',
    //         'text' => 'SMS Send with Nexmo'
    //     ]);
    // });
    Route::fallback(function(){
        abort(404);
    });
});

app/Pengumuman.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pengumuman extends Model
{
    protected $table = 'pengumuman';
    protected $fillable = ['user_id','judul','isi','lampiran','status'];
    public function user()
    {
        return $this->belongsTo('App\User', 'user_id');
    }
}

app/Http/Controllers/PengumumanController.php
<?php

namespace App\Http\Controllers;

use Auth;
use App\User;
use App\Pengumuman;
use Illuminate\Http\Request;
use App\Http\Requests\ValidatePengumuman;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class PengumumanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->ajax()) {
            $pengumuman = Pengumuman::where('status', 1)->latest()->get();
            return json_encode(['data' => $pengumuman]);
        }
        else {
            $this->authorize('index', Pengumuman::class);
            return view('pengumuman.index');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize('create', Pengumuman::class);
        return view('pengumuman.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ValidatePengumuman $request)
    {
        $status = ($request->has('status')) ? 1 : 0;
        if ($request->hasFile('lampiran')) {
            $realName = basename($request->file('lampiran')->getClientOriginalName(), '.'.$request->file('lampiran')->getClientOriginalExtension());
            $uniqueName = $realName . '_'.time().'.' . $request->file('lampiran')->getClientOriginalExtension();
            $file = $request->file('lampiran')->storeAs('public/pengumuman/lampiran', $uniqueName,'local');

            $newPengumuman = Pengumuman::create([
                'user_id'   => Auth::user()->id,
                'judul'     => $request['judul'],
                'isi'       => $request['isi'],
                'lampiran'  => $uniqueName,
                'status'    => $status
            ]);
        }
        else {
            $newPengumuman = Pengumuman::create([
                'user_id'   => Auth::user()->id,
                'judul'     => $request['judul'],
                'isi'       => $request['isi'],
                'status'    => $status
            ]);
        }
        if($newPengumuman) {
            return \Redirect::route('pengumuman.create')
                ->with('status', 'Pengumuman berhasil disimpan')
                ->with('id', $newPengumuman->id);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Pengumuman $pengumuman)
    {
        $this->authorize('view', $pengumuman);
        return view('pengumuman.show', compact('pengumuman'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Pengumuman $pengumuman)
    {
        $this->authorize('edit', $pengumuman);
        return view('pengumuman.edit', compact('pengumuman'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ValidatePengumuman $request, Pengumuman $pengumuman)
    {
        $this->authorize('update', $pengumuman);
        if($request->has('hapus-lampiran')) {
            Storage::delete('public/pengumuman/lampiran/'.$pengumuman->lampiran);
            $pengumuman->update([
                'lampiran'  => null
            ]);
        }
        if($request->hasFile('lampiran')) {
            // STORE NEW ONE
            $realName = basename($request->file('lampiran')->getClientOriginalName(), '.'.$request->file('lampiran')->getClientOriginalExtension());
            $uniqueName = $realName . '_'.time().'.' . $request->file('lampiran')->getClientOriginalExtension();
            $file = $request->file('lampiran')->storeAs('public/pengumuman/lampiran', $uniqueName,'local');

            // DELETE OLD ONE
            Storage::delete('public/pengumuman/lampiran/'.$pengumuman->lampiran);

            // UPDATE DATABASE
            $pengumuman->update([
                'lampiran'  => $uniqueName
            ]);
        }

        if($request->has('status')) {
            $pengumuman->update([
                'status'  => 1
            ]);
        }
        else {
            $pengumuman->update([
                'status'  => 0
            ]);
        }

        $pengumuman->update([
            'judul'  => $request['judul'],
            'isi'    => $request['isi']
        ]);

        if($pengumuman) {
            return back()->with('status', 'Pengumuman berhasil diupdate');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Pengumuman $pengumuman)
    {
        $this->authorize('delete', $pengumuman);
        Storage::delete('public/pengumuman/lampiran/'.$pengumuman->lampiran);
        $isDeleted = Pengumuman::destroy($pengumuman->id);
        
        if(!Pengumuman::first()) {
            DB::update("ALTER TABLE pengumuman AUTO_INCREMENT= 1");
        }
        if($isDeleted) {
            if(app('router')->getRoutes()->match(app('request')->create(\URL::previous()))->getName() == "pengumumanku") {
                return redirect()->back()->with('status', 'Pengumuman berhasil dihapus');
            }
            else {
                return redirect()->route('pengumumanku')->with('status', 'Pengumuman berhasil dihapus');
            }
        }
    }

    public function pengumumanku(Request $request) {
        if($request->ajax()) {
            $pengumuman = Pengumuman::latest()->get();
            return json_encode(['data' => $pengumuman]);
        }
        else {
            $this->authorize('pengumumanku', Pengumuman::class);
            return view('pengumuman.pengumumanku');
        }
    }

    public function updateStatus(Request $request, $id, $boolean) {
        if($request->ajax()) {
            $updated = Pengumuman::where('id', $id)->update(['status' => $boolean]);
        }
        else {
            abort(404);
        }
    }
}

resources/views/pengumuman/create.blade.php
@extends('layouts.app')
<head>
    @include('layouts.base')  
    <title>Tambah Pengumuman - Sistem Informasi Manajemen Saksi Pemilu</title>
</head>

@section('content')
<div class="row">
    <div class="col-lg"></div>
    <div class="col-lg-9">
        @if (\Session::has('status'))
            <div class="alert alert-success fade show mb-4 px-3 py-2" role="alert">
                {{ \Session::get('status') }}
                <div class="d-flex justify-content-end mt-2">
                    <a class="btn btn-small btn-light" href="{{route("pengumuman.show",\Session::get('id'))}}">Lihat Pengumuman</a>
                </div>
            </div>
        @endif
        @if ($errors->any())
            <div class="alert alert-danger fade show mb-4 px-3 py-2" role="alert">
                {{ $errors->first() }}
            </div>
        @endif
        
        <form method="POST" action="{{route('pengumuman.store')}}" enctype="multipart/form-data">
            @csrf
            <h3 class="text-center"><strong>Tambah Pengumuman</strong></h3>
        
            <div class="form-group">
                <label class="text-muted mt-3" for="judul">Judul Pengumuman</label>
                <input type="text" name="judul" class="form-control" id="judul" maxlength="100" required autofocus>
            </div>
        
            <div class="form-group">
                <label class="text-muted mt-3" for="isi">Isi Pengumuman</label>
                <textarea class="form-control" id="isi" name="isi" rows="6" maxlength="500" required></textarea>
            </div>
        
            <label class="text-muted mt-3" for="lampiran">Lampiran</label>
            <div class="custom-file my-1">
                <input id="lampiran" type="file" class="custom-file-input" name="lampiran" accept="*">
                <label class="custom-file-label" for="lampiran">Tidak ada file yang dipilih</label>
            </div>

            <div class="form-group mt-5 mb-0">
                <div class="d-flex align-items-center">
                    <small class="m-0 text-muted">Hide</small>
                    <label class="switch my-0 mx-2" title="Aktif/Tidak Aktif">
                        <input type="checkbox" class="active-switch" name="status" checked>
                        <span class="slider"></span>
                    </label>
                    <small class="m-0 text-muted">Show</small>
                </div>
            </div>

            <div class="row">
                <div class="col"></div>
                <div class="col-lg-4 col-md-4 col-sm-8 mt-3">
                    <button type="submit" class="btn btn-success btn-lg btn-block mt-4 font-weight-bold">SIMPAN</button>
                </div>
            </div>
        </form>
    </div>
    <div class="col-lg"></div>
</div>
@endsection

resources/views/pengumuman/edit.blade.php
@extends('layouts.app')
<head>
    @include('layouts.base')  
    <title>Edit Pengumuman - Sistem Informasi Manajemen Saksi Pemilu</title>
</head>

@section('content')
<div class="row">
    <div class="col-lg"></div>
    <div class="col-lg-9">
        @if (\Session::has('status'))
            <div class="alert alert-success fade show mb-4 px-3 py-2" role="alert">
                {{ \Session::get('status') }}
                <div class="d-flex justify-content-end mt-2">
                    <a class="btn btn-small btn-light" href="{{route("pengumuman.show",$pengumuman->id)}}">Lihat Pengumuman</a>
                </div>
            </div>
        @endif
        @if ($errors->any())
            <div class="alert alert-danger fade show mb-4 px-3 py-2" role="alert">
                {{ $errors->first() }}
            </div>
        @endif
        <!-- KOORDINATOR SAKSI -->
        <form method="POST" action="{{route('pengumuman.update', $pengumuman->id)}}" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <h3 class="text-center"><strong>Edit Pengumuman</strong></h3>
        
            <div class="form-group">
                <label class="text-muted mt-3" for="judul">Judul Pengumuman</label>
                <input type="text" name="judul" class="form-control" id="judul" value="{{$pengumuman->judul}}" required>
            </div>
        
            <div class="form-group">
                <label class="text-muted mt-3" for="isi">Isi Pengumuman</label>
                <textarea class="form-control" id="isi" name="isi" rows="6" maxlength="500" required>{{$pengumuman->isi}}</textarea>
            </div>
        
            <label class="text-muted mt-3" for="lampiran">Lampiran</label><br>
            <div class="custom-file my-1">
                <input id="lampiran" type="file" class="custom-file-input" name="lampiran" accept="*">
                <label class="custom-file-label" for="lampiran">Pilih file lampiran</label>
            </div>
            @if($pengumuman->lampiran)
            <div class="d-flex flex-sm-row flex-column">
                <a href="{{ asset("storage/pengumuman/lampiran/{$pengumuman->lampiran}") }}" class="btn btn-small btn-secondary m-1" title="{{$pengumuman->lampiran}}">
                    Lihat Lampiran
                </a>
                <a id="hapus-lampiran" href="#" class="btn btn-small btn-danger m-1" title="Hapus Lampiran" data-toggle="modal" data-target="#modal-hapus-lampiran">
                    Hapus Lampiran
                </a>
            </div>
            @else
            <small class="text-muted">Pengumuman ini tidak memiliki lampiran</small>
            @endif

            
            <!-- Modal Hapus Lampiran-->
            <div class="modal fade" id="modal-hapus-lampiran" tabindex="-1" role="dialog" aria-labelledby="modalTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered modal-dialog modal-sm" role="document">
                    <div class="modal-content border-0">
                        <div class="modal-body p-4">
                            <h5 class="font-weight-bold m-0">Hapus lampiran di pengumuman ini?</h5>
                        </div>
                        <div class="modal-footer border-0">
                            <button type="button" class="btn btn-light mr-2" data-dismiss="modal">Tidak</button>
                            <button type="submit" class="btn btn-danger">Hapus</button>
                        </div>
                    </div>
                </div>
            </div>

            <div class="form-group mt-5 mb-0">
                <div class="d-flex align-items-center">
                    <small class="m-0 text-muted">Hide</small>
                    <label class="switch my-0 mx-2" title="Aktif/Tidak Aktif">
                        <input type="checkbox" class="active-switch" name="status" {{ ( $pengumuman->status == 1 ) ? 'checked' : '' }}>
                        <span class="slider"></span>
                    </label>
                    <small class="m-0 text-muted">Show</small>
                </div>
            </div>
    
            <div class="row">
                <div class="col"></div>
                <div class="col-lg-4 col-md-4 col-sm-8 mt-3">
                    <button type="submit" class="btn btn-success btn-lg btn-block mt-4 font-weight-bold">SIMPAN</button>
                </div>
            </div>
        </form>
    </div>
    <div class="col-lg"></div>
</div>
<script>
    $("#hapus-lampiran").on('click', function () {
        $("form").append('<input name="hapus-lampiran" type="hidden" value="">');
    });
</script>
@endsection

resources/views/pengumuman/index.blade.php
@extends('layouts.app')
<head>
    @include('layouts.base')
    @include('layouts.datatable-css')
    @include('layouts.datatable-js')
    @include('layouts.datatable-btn-js')
    <title>Pengumuman - Sistem Informasi Manajemen Saksi Pemilu</title>
    <meta name="csrf-token" content="{{ csrf_token() }}" />
</head>

@section('content')
<div class="row">
    <div class="col-md-1"></div>
    <div class="col">        
        <h3 class="text-center"><strong>Pengumuman</strong></h3>
    </div>
    <div class="col-md-1"></div>
</div>

<div class="row">
    <div class="col-md-1"></div>
    <div class="col">
        <hr>
        <div class="d-flex flex-column flex-sm-row justify-content-between align-content-center">
            <form id="global-search-form" class="d-flex flex-fill align-items-center p-0 mb-2">
                <i class="mdi mdi-magnify mdi-24px pr-1"></i>
                <input id="globalSearch" class="form-control m-0" type="text" placeholder="Cari" maxlength="100">
            </form>
        </div>
    </div>
    <div class="col-md-1"></div>
</div>

<div class="row">
    <div class="col-md-1"></div>
    <div class="col">
        <div class="table-responsive">
            <table id="tabel-pengumuman" class="table" style="width:100%">
                <thead>
                    <tr>
                        <th>Judul</th>
                        <th>Isi</th>
                        <th>Tanggal</th>
                        <th>Lampiran</th>
                        <th>Aksi</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
    <div class="col-md-1"></div>
</div>
        
<div class="d-flex flex-column">
    <div id="tableInfo" class="d-flex justify-content-center my-2"></div>
    <div id="tablePage" class="d-flex justify-content-center"></div>
</div>


<script>
    $(document).ready(function() {
        $.fn.DataTable.ext.pager.numbers_length = 5;
        var table = $('#tabel-pengumuman').DataTable({
            processing: true,
            ajax: '{{route("pengumuman.index")}}',
            columns: [
                { "data": "judul" },
                { "data": "isi" },
                { "data": "created_at" },
                { "data": "lampiran" },
                { "data": "id" },
            ],
            columnDefs: [
                {
                    targets: 0,
                    render: $.fn.dataTable.render.ellipsis(50)
                },
                {
                    targets: 1,
                    render: $.fn.dataTable.render.ellipsis(50)
                },
                {
                    "targets": 2,
                    "data": "created_at",
                    "render": function ( data, type, row, meta ) {
                        var date = new Date(data);
                        var options = { year: 'numeric', month: 'long', day: 'numeric' };
                        return date.toLocaleDateString('id', options);
                    }
                },
                {
                    "targets": 3,
                    "data": "lampiran",
                    "render": function ( data, type, row, meta ) {
                        if(data != null) {
                            return '<i class="mdi mdi-attachment" title="Ada Lampiran"></i>';
                        }
                        else {
                            return data;
                        }
                    }
                },
                {
                    "targets": 4,
                    "data": "id",
                    "render": function ( data, type, row, meta ) {
                        return '<a href="pengumuman/'+data+'" class="btn btn-small btn-secondary" title="Lihat Detail">Detail</a>';
                    }
                },
                
                {  className: "judul font-weight-bold pt-0 pb-2 px-0", targets: 0 },
                {  className: "pt-0 pb-2 px-0", targets: 1 },
                {  className: "date pt-0 pb-2 px-0 text-muted", targets: 2 },
                {  className: "px-0 py-0", targets: 3 },
                {  className: "d-flex flex-grow-1 align-items-end justify-content-end p-0 mt-2", targets: 4 }
            ],
            order: [],
            autoWidth: true,
            language: {
                "info": "_START_-_END_ dari _TOTAL_ data",
                "infoEmpty":  "Tidak Ada Data",
                "emptyTable": "Tidak ada data yang tersedia",
                "lengthMenu": "Tampilkan _MENU_ data",
                "thousands":      ".",
                'loadingRecords': '&nbsp;',
                "processing": "<div class='spinner'></div>",
                "search":     "Cari:",
                "zeroRecords":"Tidak ada data",
                "infoFiltered":   "(disaring dari total _MAX_ data)",
                "paginate": {
                    "next":       "<i class='mdi mdi-chevron-right'></i>",
                    "previous":   "<i class='mdi mdi-chevron-left'></i>"
                },
            },
            pagingType: "simple_numbers",
            pageLength: 8,
            lengthChange: false,
            dom: 'rt<"row"<"col-sm-12 col-md-5"i><"col-sm-12 col-md-7"p>>',
            createdRow: function ( row, data, index ) {
                $(row).addClass('card card-radius p-3 mb-3 d-flex flex-column')
            },
        });

        // TABLE SEARCH (GLOBAL)
        $('#globalSearch').on( 'keyup', function () {
            table.search( this.value ).draw();
        });
        $( table.table().body() )
            .addClass( 'd-flex flex-column flex-sm-row flex-wrap justify-content-between p-1' );

        $('.dataTables_paginate').appendTo('#tablePage');
        $('.dataTables_info').appendTo('#tableInfo');
        $("#global-search-form").submit(function(e){
            e.preventDefault();
        });
        $(document).on('click', '.btn-delete', function () {
            var url = $(this).attr("data-url");
            $(".delete-form").attr("action", url);
        });
        $('.active-switch').click(function(){
            if (this.checked) {
                alert('aktif');
            }
            else {
                alert('tidak aktif');
            }
        }) 
    });
</script>
@endsection

resources/views/pengumuman/show.blade.php
@extends('layouts.app')
<head>
    @include('layouts.base')
    <title>Detail Pengumuman - Sistem Informasi Manajemen Saksi Pemilu</title>
    <meta name="csrf-token" content="{{ csrf_token() }}" />
</head>

@section('content')
<div class="d-flex justify-content-center">
    <div class="d-flex flex-container flex-column">
        @if (\Session::has('status'))
        <div class="alert alert-success fade show mb-4 px-3 py-2" role="alert">
            {{ \Session::get('status') }}
        </div>
        @endif
        @if ($errors->any())
            <div class="alert alert-danger fade show mb-4 px-3 py-2" role="alert">
                {{ $errors->first() }}
            </div>
        @endif
        <div class="d-flex justify-content-center">
            <h3 class="m-0 text-center"><strong>Detail Pengumuman</strong></h3>
        </div>
        <hr>
        @if($pengumuman->user_id === Auth::user()->id)
        <div class="d-flex flex-row justify-content-end mb-3">
            <a class="btn btn-success mr-2" href="{{route('pengumuman.edit', $pengumuman->id)}}" title="Edit">
                <i class="mdi mdi-pencil"></i> Edit
            </a>
            <button type="button" class="btn btn-danger" title="Hapus" data-toggle="modal" data-target="#modalHapus">
                <i class="mdi mdi-delete"></i> Hapus
            </button>
            <!-- Modal Hapus-->
            <div class="modal fade" id="modalHapus" tabindex="-1" role="dialog" aria-labelledby="modalTitle" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered modal-dialog modal-sm" role="document">
                    <div class="modal-content border-0">
                        <div class="modal-body p-4">
                            <h5 class="font-weight-bold m-0">Hapus Pengumuman ini?</h5>
                        </div>
                        <div class="modal-footer border-0">
                            <button type="button" class="btn btn-light mr-2" data-dismiss="modal">Tidak</button>
                            <form action="{{route('pengumuman.destroy', $pengumuman->id)}}" method="POST" class="m-0">
                                @csrf
                                @method('DELETE')
                                <input name="_method" type="hidden" value="DELETE">
                                <button type="submit" class="btn btn-danger">Hapus</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @endif
        <div class="d-flex flex-column flex-sm-row justify-content-between">
            <div class="d-flex flex-column flex-fill">
                <div class="card card-radius card-margin p-4 m-0">
                    <h5 class="m-0 font-weight-bold">{{$pengumuman->judul}}</h5>
    
                    <p class="mt-2">{{$pengumuman->isi}}</p>

                    <small class="text-muted">Dibuat pada {{$pengumuman->created_at->format('d F Y')}}</small>
                    <div class="d-flex justify-content-end">
                        @if($pengumuman->lampiran != null)
                        <a href="{{ asset("storage/pengumuman/lampiran/{$pengumuman->lampiran}") }}" class="btn btn-secondary mt-3">
                           <i class="mdi mdi-download"></i> Download Lampiran
                        </a>
                        @else
                        <small class="text-muted">Tidak ada lampiran</small>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection