routes/web.php
<?php
use App\UserType;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

 // Authentication Routes...
 Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
 Route::post('login', 'Auth\LoginController@login');
 Route::post('logout', 'Auth\LoginController@logout')->name('logout');

//  // Registration Routes...
//  Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
//  Route::post('register', 'Auth\RegisterController@register');

//  // Password Reset Routes...
//  Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
//  Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
//  Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
//  Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::group(['middleware' => 'auth'], function()
{
    Route::redirect('/', '/target');
    Route::get('mykoor', 'KoorController@myKoor')->name('mykoor');
    Route::get('mysaksi', 'SaksiController@mySaksi')->name('mysaksi');
    Route::get('pengumumanku', 'PengumumanController@pengumumanku')->name('pengumumanku');
    Route::get('c1saya', 'C1Controller@c1Saya')->name('c1saya');
    Route::get('akunsaya', 'UserController@akunSaya')->name('akunsaya');
    Route::get('akunsaya/edit', 'UserController@editProfilSaya')->name('editprofil');
    Route::get('/kel/{id}', 'SaksiController@getKoor')->name('getkoor');
    Route::get('/checkpassword/{password}', 'UserController@checkPassword')->name('checkpassword');
    Route::get('/statuspengumuman/{id}/{boolean}', 'PengumumanController@updateStatus')->name('statuspengumuman');

    Route::resource('koor', 'KoorController');
    Route::resource('saksi', 'SaksiController');
    Route::resource('pengumuman', 'PengumumanController');
    Route::resource('user', 'UserController')->only([
        'index', 'show', 'update'
    ]);
    Route::resource('partai', 'PartaiController')->except(['show']);
    Route::resource('c1', 'C1Controller')->except(['show']);
    Route::resource('target', 'TargetController')->only([
        'index', 'edit', 'update'
    ]);
    // Route::get('/sms', function () {
    //     Nexmo::message()->send([
    //         'to'   => '6282247973615',
    //         'from' => '15556666666',
    //         'text' => 'SMS Send with Nexmo'
    //     ]);
    // });
    Route::fallback(function(){
        abort(404);
    });
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="id">

  <body>
    @include('layouts.navbar')

    <div class="container-fluid">
      <div class="row">
        @include('layouts.sidenav')

        <div id="overlay"></div>
        
        <div id="main" class="col">
          @yield('content')
        </div>

      </div>
    </div>
  </body>
</html>

resources/views/layouts/base.blade.php
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<link rel="icon" type="image/png" href="{{ asset('storage/img/favicon.png') }}">

<link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ asset('css/style.css') }}">
<link rel="stylesheet" href="{{ asset('css/materialdesignicons.min.css') }}" media="all" type="text/css" />


<script src="{{ asset('js/jquery-3.3.1.min.js') }}"></script>
<script src="{{ asset('js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('js/script.js') }}"></script>

resources/views/layouts/datatable-btn-js.blade.php
<script type="text/javascript" src="{{ asset('DataTables/Buttons-1.5.4/js/dataTables.buttons.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('DataTables/Buttons-1.5.4/js/buttons.bootstrap4.min.js') }}"></script>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script type="text/javascript" src="{{ asset('DataTables/pdfmake-0.1.36/pdfmake.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('DataTables/pdfmake-0.1.36/vfs_fonts.js') }}"></script>
<script type="text/javascript" src="{{ asset('DataTables/Buttons-1.5.4/js/buttons.html5.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('DataTables/Buttons-1.5.4/js/buttons.print.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('DataTables/Buttons-1.5.4/js/buttons.colVis.min.js') }}"></script>

resources/views/layouts/datatable-css.blade.php
<link rel="stylesheet" type="text/css" href="{{ asset('DataTables/DataTables-1.10.18/css/dataTables.bootstrap4.min.css') }}"/>
<link rel="stylesheet" type="text/css" href="{{ asset('DataTables/FixedColumns-3.2.5/css/fixedColumns.bootstrap4.min.css') }}"/>
<link rel="stylesheet" type="text/css" href="{{ asset('DataTables/Buttons-1.5.4/css/buttons.bootstrap4.min.css') }}"/>
{{-- SELECT2 --}}
<link rel="stylesheet" type="text/css" href="{{ asset('css/select2.min.css') }}"/>

resources/views/layouts/datatable-fixedcolumn.blade.php
<script type="text/javascript" src="{{ asset('DataTables/FixedColumns-3.2.5/js/dataTables.fixedColumns.min.js') }}"></script>

resources/views/layouts/datatable-js.blade.php
<script type="text/javascript" src="{{ asset('DataTables/DataTables-1.10.18/js/jquery.dataTables.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('DataTables/DataTables-1.10.18/js/dataTables.bootstrap4.min.js') }}"></script>
<script type="text/javascript" src="http://cdn.datatables.net/plug-ins/1.10.19/dataRender/ellipsis.js"></script>

resources/views/layouts/navbar.blade.php
<nav class="navbar fixed-top d-flex flex-row align-items-stretch">
  <div id="real-navbar" class="d-flex w-100">
    <div class="d-flex align-content-stretch flex-wrap">
        <button id="btn-sidenav" type="button" class="btn btn-navbar align-self-center"><i class="mdi mdi-menu mdi-24px"></i></button>
    </div>
    <div class="d-flex align-content-stretch w-100">
        <img class="brand align-self-center mr-2" src="{{ URL::asset('storage/img/logo-white.png') }}" alt="logo" height="25">
        <h5 class="brand d-none d-md-block font-weight-bold m-0 align-self-center">Sistem Informasi Manajemen Saksi Pemilu</h5>
        <p class="brand d-sm-block d-md-none font-weight-bold m-0 align-self-center">Sistem Informasi <br/> Manajemen Saksi Pemilu</p>
    </div>
    @if(Auth::user()->is(1) || Auth::user()->is(2) || Auth::user()->is(4))
        <button id="btn-tambah" class="btn btn-navbar d-flex align-content-stretch" type="button" title="Tambah Data" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="mdi mdi-plus-box-outline mdi-24px"></i>
        </button>
        <div id="dropdownAdd" class="dropdown-menu dropdown-menu-right border-0">
            @if(Auth::user()->is(2))
                <a class="dropdown-item d-flex align-content-stretch flex-wrap" href="{{route('saksi.create')}}">
                    <div class="align-self-center">
                        <i class="mdi mdi-account-multiple-plus mdi-24px"></i>
                    </div>
                    <div class="align-self-center link-name">
                        Saksi
                    </div>
                </a>
                <a class="dropdown-item d-flex align-content-stretch flex-wrap" href="{{route('koor.create')}}">
                    <div class="align-self-center">
                        <i class="mdi mdi-account-plus mdi-24px"></i>
                    </div>
                    <div class="align-self-center link-name">
                        Koordinator Saksi
                    </div>
                </a>
            @elseif(Auth::user()->is(1))
                <a class="dropdown-item d-flex align-content-stretch flex-wrap" href="{{route('pengumuman.create')}}">
                    <div class="align-self-center">
                        <i class="mdi mdi-bullhorn mdi-24px"></i>
                    </div>
                    <div class="align-self-center link-name">
                        Pengumuman
                    </div>
                </a>
                <a class="dropdown-item d-flex align-content-stretch flex-wrap" href="{{route('partai.create')}}">
                    <div class="align-self-center">
                        <i class="mdi mdi-flag mdi-24px"></i>
                    </div>
                    <div class="align-self-center link-name">
                        Partai
                    </div>
                </a>
            @elseif(Auth::user()->is(4))
                <a class="dropdown-item d-flex align-content-stretch flex-wrap" href="{{route('c1.create')}}">
                    <div class="align-self-center">
                        <i class="mdi mdi-file-image mdi-24px"></i>
                    </div>
                    <div class="align-self-center link-name">
                        Foto C1
                    </div>
                </a>
            @endif
        </div>
    @endif
  </div>
</nav>

resources/views/layouts/sidenav.blade.php
<div id="side-nav" class="col p-0">
  <ul class="nav mb-2">
    <li id="account-container" class="nav-item d-flex flex-row">
        @if(Auth::user()->is(1) || Auth::user()->is(2))
        <i class="mdi mdi-account-circle mdi-24px align-self-center"></i>
        @elseif(Auth::user()->is(3))
        <div class="avatar-container">
            <img src="{{ asset('storage/koor/foto_diri/'.Auth::user()->koor->foto_diri) }}" class="avatar" alt="foto profil">
        </div>
        @elseif(Auth::user()->is(4))
        <div class="avatar-container">
            <img src="{{ asset('storage/saksi/foto_diri/'.Auth::user()->saksi->foto_diri) }}" class="avatar" alt="foto profil">
        </div>
        @endif
        <div id="account-info" class="align-self-center flex-grow-1">
            @if(Auth::user()->is(1))
                <p class="mx-0 mb-1 font-weight-bold">{{Auth::user()->role->name}}</p>
                <small class="text-muted role1">{{Auth::user()->role->name}}</small>
            @elseif(Auth::user()->is(2))
                <p class="mx-0 mb-1 font-weight-bold" title="{{Auth::user()->komisisaksi->nama}}">
                    {{str_limit(Auth::user()->komisisaksi->nama, 15)}}
                </p>
                <small class="text-muted role2">{{Auth::user()->role->name}}</small>
            @elseif(Auth::user()->is(3))
                <p class="mx-0 mb-1 font-weight-bold">{{\Illuminate\Support\Str::words(Auth::user()->koor->nama, 2,'')}}</p>
                <small class="text-muted role3">{{Auth::user()->role->name}}</small>
            @elseif(Auth::user()->is(4))
                <p class="mx-0 mb-1 font-weight-bold">{{\Illuminate\Support\Str::words(Auth::user()->saksi->nama, 2,'')}}</p>
                <small class="text-muted role4">{{Auth::user()->role->name}}</small>
            @endif
        </div>
    </li>
    <hr class="mb-2 mt-0">
    @if(Auth::user()->is(1) || Auth::user()->is(2))
    <li class="nav-item {{ request()->is('target*') ? 'active-nav' : '' }}">
      <a class="nav-link d-flex align-content-stretch flex-wrap" href="{{ route('target.index') }}" title="Lihat Kemajuan Target">
        <div class="align-self-center">
          <i class="mdi mdi-finance mdi-24px"></i>
        </div>
        <div class="align-self-center link-name">
          Target
        </div>
      </a>
    </li>
    <li class="nav-item {{ request()->is('saksi*') ? 'active-nav' : '' }}">
        <a class="nav-link d-flex align-content-stretch flex-wrap" href="{{route('saksi.index')}}" title="Semua Saksi">
        <div class="align-self-center">
          <i class="mdi mdi-account-group mdi-24px"></i>
        </div>
        <div class="align-self-center link-name">
          Saksi
        </div>
      </a>
    </li>
    <li class="nav-item {{ request()->is('koor*') ? 'active-nav' : '' }}">
      <a class="nav-link d-flex align-content-stretch flex-wrap" href="{{ route('koor.index') }}" title="Semua Koordinator Saksi">
        <div class="align-self-center">
          <i class="mdi mdi-account-multiple mdi-24px"></i>
        </div>
        <div class="align-self-center link-name">
          Koordinator Saksi
        </div>
      </a>
    </li>
    @endif
    
    @if(Auth::user()->role_id !== 1)
    <li class="nav-item {{ request()->is('pengumuman*') ? 'active-nav' : '' }}">
      <a class="nav-link d-flex align-content-stretch flex-wrap" href="{{route('pengumuman.index')}}" title="Pengumuman">
        <div class="align-self-center">
          <i class="mdi mdi-bullhorn mdi-24px"></i>
        </div>
        <div class="align-self-center link-name">
          Pengumuman
        </div>
      </a>
    </li>
    @endif

    @if(Auth::user()->is(4))
    <li class="nav-item {{ request()->is('c1*') ? 'active-nav' : '' }}">
        <a class="nav-link d-flex align-content-stretch flex-wrap" href="{{route('c1saya')}}" title="Pengumuman">
          <div class="align-self-center">
            <i class="mdi mdi-file-image mdi-24px"></i>
          </div>
          <div class="align-self-center link-name">
            Foto C1 Saya
          </div>
        </a>
    </li>
    @endif

    @if(Auth::user()->is(2))
    <li class="nav-item {{ request()->is('mysaksi') ? 'active-nav' : '' }}">
      <a class="nav-link d-flex align-content-stretch flex-wrap" href="{{route('mysaksi')}}" title="Daftar Saksi Saya">
        <div class="align-self-center">
          <i class="mdi mdi-account-supervisor mdi-24px"></i>
        </div>
        <div class="align-self-center link-name">
          Saksi Saya
        </div>
      </a>
    </li>
    <li class="nav-item {{ request()->is('mykoor') ? 'active-nav' : '' }}">
        <a class="nav-link d-flex align-content-stretch flex-wrap" href="{{route('mykoor')}}" title="Daftar Koordinator Saksi Saya">
        <div class="align-self-center">
          <i class="mdi mdi-account-supervisor-circle mdi-24px"></i>
        </div>
        <div class="align-self-center link-name">
          Koordinator Saya
        </div>
      </a>
    </li>
    @endif

    @if(Auth::user()->is(1))
    <li class="nav-item {{ request()->is('pengumuman*') ? 'active-nav' : '' }}">
        <a class="nav-link d-flex align-content-stretch flex-wrap" href="{{route('pengumumanku')}}" title="Pengumuman">
            <div class="align-self-center">
            <i class="mdi mdi-bullhorn mdi-24px"></i>
            </div>
            <div class="align-self-center link-name">
            Pengumumanku
            </div>
        </a>
    </li>
    <li class="nav-item {{ request()->is('c1*') ? 'active-nav' : '' }}">
        <a class="nav-link d-flex align-content-stretch flex-wrap" href="{{route('c1.index')}}" title="Pengumuman">
            <div class="align-self-center">
            <i class="mdi mdi-file-image mdi-24px"></i>
            </div>
            <div class="align-self-center link-name">
            Foto C1
            </div>
        </a>
    </li>
    <li class="nav-item {{ request()->is('user*') ? 'active-nav' : '' }}">
      <a class="nav-link d-flex align-content-stretch flex-wrap" href="{{route('user.index')}}" title="Daftar Pengguna">
        <div class="align-self-center">
          <i class="mdi mdi-account-box-multiple mdi-24px"></i>
        </div>
        <div class="align-self-center link-name">
          Pengguna
        </div>
      </a>
    </li>
    <li class="nav-item {{ request()->is('partai*') ? 'active-nav' : '' }}">
      <a class="nav-link d-flex align-content-stretch flex-wrap" href="{{route('partai.index')}}" title="Daftar Partai">
        <div class="align-self-center">
          <i class="mdi mdi-flag mdi-24px"></i>
        </div>
        <div class="align-self-center link-name">
          Partai
        </div>
      </a>
    </li>
    @endif
    
    <li class="nav-item {{ request()->is('akunsaya*') ? 'active-nav' : '' }}">
      <a class="nav-link d-flex align-content-stretch flex-wrap" href="{{route('akunsaya')}}" title="Akun Saya">
        <div class="align-self-center">
          <i class="mdi mdi-account-details mdi-24px"></i>
        </div>
        <div class="align-self-center link-name">
          Akun Saya
        </div>
      </a>
    </li>
    <li class="nav-item">
      <a id="logout" class="nav-link d-flex align-content-stretch flex-wrap" 
      href="{{ route('logout') }}"
      onclick="event.preventDefault();
      document.getElementById('logout-form').submit();" title="Logout">
        <div class="align-self-center">
          <i class="mdi mdi-logout-variant mdi-24px"></i>
        </div>
        <div class="align-self-center link-name">
          Logout
        </div>
      </a>
      <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
        @csrf
      </form>
    </li>
  </ul>
</div>